version: '3.5'

services:
  laravel-app:
    image: php:8.1-apache
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - backend
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laraveluser
      - MYSQL_PASSWORD=laravelpassword
    networks:
      - backend

networks:
  backend:
    name: backend-network